### ISSUE TITLE
make a colab for hosting the back easily

### ISSUE THREAD

**Issue by rom1504** [rom1504/dalle-service#2]
https://github.com/rom1504/dalle-service/tree/master/back
https://medium.com/@kshitijvijay271199/flask-on-google-colab-f6525986797b

**Comment by johnpaulbin** [comment]
Hey, mega b here.
I found a better solution to ngrok, it uses localtunnel.me. It has a much longer session time, and is not limited to 20 requests a minute.
Example code:

`!npm install -g localtunnel`

```python

from threading import Thread

def app():
  !python app.py # MAKE SURE: It is open to the port 8000.

if __name__ == '__main__':
    t1 = Thread(target = app)
    a = t1.start()
```

Then another cell with:
`!lt --port 8000`

Hope this helps.

**Comment by rom1504** [comment]
yeah that seems pretty good indeed!
I'll make that colab soon

**Comment by rom1504** [comment]
done https://colab.research.google.com/github/rom1504/dalle-service/blob/master/dalle_back.ipynb
