### ISSUE TITLE
deploy on openfaas.louis030195.com

### ISSUE THREAD

**Issue by louis030195** [rom1504/dalle-service#3]
I have a Openfaas deployed on my k8s cluster, though, low compute yet, do you need a lot of compute to run the backend? GPU?
https://www.openfaas.com/blog/openfaas-flask/

**Comment by rom1504** [comment]
yeah the backend needs a gpu. I think 2GB of vram should be enough
it might be slower on low end GPU though
on high ends GPU a batch of 4 images take 10s

**Comment by louis030195** [comment]
I have a GTX970m in the cluster, but it needs some configuration and IDK how Openfaas use GPUs, I'll take a look what I can do
