### ISSUE TITLE
Update to dalle_back.ipynb

### ISSUE THREAD

**Issue by OlegKitGit** [rom1504/dalle-service#9]
#@title # Setup, run this once
from IPython.display import clear_output
!sudo apt-get -y install llvm-9-dev cmake
!pip install Deepspeed
!npm install -g localtunnel
clear_output()
%cd /content/
!pip install keras==2.4.0 Flask==1.1.2 Flask-Cors==3.0.9 Flask-RESTful==0.3.8 dalle-pytorch==0.13.4 tqdm triton==0.4.2
!git clone https://github.com/rom1504/dalle-service.git
clear_output()
print("Finished setup.")

**Comment by rom1504** [comment]
what is the update ?
